DEFAULT_COL_MAX = 4
DEFAULT_COL_MIN = 4
DEFAULT_ROW_MAX = 5
DEFAULT_ROW_MIN = 3

DEFAULT_NUM_MIN = 3
DEFAULT_NUM_MAX = 4

DEFAULT_INDENT_MIN = 2
DEFAULT_INDENT_MAX = 5

TITLE_COLOR = (235, 119, 46)
TITLE_FONT_SIZE = 60
TEXT_FONT_SIZE = 52

PAPER_WIDTH = 3000
PAPER_OFFSET = 400
HOR_GAP_WIDTH = 80
VER_GAP_HEIGHT = 40
