通用:
  f1: 卡号 账号



建行:
  表头: 卡号 户名 起始日期 终止日期
  条目: 卡号 摘要 交易金额 账户余额 交易日期 记账日期 商户/网点号及名称
工行:
  表头: 卡号 户名 起始日期 截止日期 授权柜员号 操作柜员 操作网点 操作地区
  条目: 工作日期 账号 应用号 序号 币种 钞汇 交易代码 注释 借贷 发生额 余额 存期 约转期 通知种类/发行代码 利息税 起息日 止息日 地区号 网点号 操作员 界面
农行:
  表头: 打印机构 打印日期 页码 姓名 卡号 账号序号 币种
  条目: 日期 地点 摘要 存入 支出 余额
中行:
  表头: 打印日期 打印网点 打印柜员 账号 客户号 账户名 开户日期 开户行 产品大类 产品子类 起息日 到期日
  条目: 交易日 网点 交易代码 货币号 交易金额 交易余额 摘要 交易类别 对方账号 冲正 过账日期柜员 交易名称
农信存折:
  表头: 账号 起始日期 终止日期 明细号 客户名称
  条目: 币别 借方发生额 贷方发生额 活存账户余额 备注 交易日期
农信卡:
  表头: 户名 卡号
  条目: 账户类型 交易名称 交易日期 币种 借贷 交易金额 余额 柜员号 交易卡号/账号
招行:
  表头: 起始日期 终止日期 网点名称 呼口号 户口名称 打印经办 打印网点 打印日期
  条目: 记账日期 账户代码 货币 交易金额 联机余额 交易流水号 冲补账 柜员 摘要代码
民生:
  表头: 姓名 卡号 卡级别 打印日期 主卡卡号 币种 终止日期 起始日期
  条目: 交易账户 交易日期 交易时间 交易种类 交易金额 账户余额 柜员
中信:
  表头: 借记卡卡号 客户姓名 打印日期 起始日期 终止日期
  条目: 账号 交易日期 现转 支取金额 存入金额 账号余额 摘要 柜员交易号
邮政存储:
  表头: 户名 卡号 储 开户机构
  条目: 交易日期 摘要 交易金额 账户余额 交易局号
平安:
  表头: 户主 账号/卡号 开户网点 打印网点 打印日期 币种
  条目: 交易日期 交易网点 起息日 摘要 借方发生额 贷方发生额 账户余额
交通银行:
  表头: 账号/卡号 户名 查询起日 查询止日 查询时间 币种 查询柜员
  条目: 交易日期 记账日期 交易地点 交易类型 交易金额 余额
兴业:
  表头: 打印日期 户名 账号
  条目: 日期 凭证号 摘要 借方 贷方 余额 交易柜员
浦发:
  表头: 姓名 打印日期 卡号 卡级别 主卡卡号 币种 起始日期 终止日期 柜员流水号
  条目: 交易账户 交易日期 入账日期 交易摘要 交易金额 账户余额 柜员流水
光大:
  表头: 打印日期 主卡号 开始对账日期 结束对账日期 存期 存款种类 发卡行 记录状态 柜员号 姓名 开户日期 到期日 币种
  条目: 卡号 交易日期 交易地点 存入金额 支出金额 账户余额 交易摘要
农村信用社:
  表头: 卡号 户主 打印日期
  条目: 交易日期 分账号 凭证号码 摘要 发生额 余额 交易网点 交易来源
招商银行:
  表头: 户口号 姓名 终止日期 开户网点 起始日 打印经办人 打印网点 打印日期
  条目: 记账日期 货币 交易金额 联机余额 交易描述
