Consolidated Balance Sheet:
  Liquid Assets:
    Money funds
    Settlement provisions
    Loan funds
    Tradable financial assets
    Derivative financial assets
    bill receivable
    accounts receivable
    Receivables Financing
    Prepayments
    Premiums receivable
    Reinsurance accounts receivable
    Reinsurance contract reserves receivable
    Other receivables
    Interest receivable
    Dividends receivable
    Repurchase of resale financial assets
    stock
    contract assets
    Assets held for sale
    Non-current assets due within one year
    Other current assets
    Total current assets
  Non-current assets:
    Disbursement of loans and advances
    Debt investment
    Other debt investments
    Long-term receivables
    long-term equity investment
    Investment in other equity instruments
    Other non-current financial assets
    investment real estate
    fixed assets
    Construction in progress
    productive biological assets
    oil and gas asset
    right-of-use asset
    intangible assets
    Development expenditure
    goodwill
    Long-term prepaid expenses
    Deferred tax assets
    Other non-current assets
    Total non-current assets
    total assets
  Current liabilities:
    short-term loan
    borrowing from the central bank
    borrowed funds
    Held-for-trading financial liabilities
    Derivative financial liabilities
    bills payable
    accounts payable
    advance payment
    contract liabilities
    Financial assets sold under repurchase
    Deposits and deposits
    Agent for buying and selling securities
    Agent underwriting securities
    Payroll payable
    Taxes payable
    Other payables
    Interest payable
    dividends payable
    Fees and commissions
    Reinsurance Accounts Payable
    held-for-sale liabilities
    Non-current liabilities due within one year
    Other current liabilities
    Total current liabilities
  Non-current liabilities:
    Insurance contract reserve
    Long term loan
    Bonds payable
    preferred stock
    perpetual bond
    lease liability
    Long-term payables
    Long-term employee compensation payable
    Estimated liabilities
    Deferred income
    Deferred tax liabilities
    Other non-current liabilities
    Total non-current liabilities
    Total Liabilities
  Owner's Equity (or Shareholders' Equity):
    Paid-up capital (or share capital)
    Other equity instruments
    preferred stock
    perpetual bond
    capital reserve
    treasury stocks
    Other comprehensive income
    Special reserves
    surplus reserve
    general risk preparation
    undistributed profit
    Total owner's equity (or shareholders' equity) attributable to the parent company
    Minority interests
    Total owner's equity (or shareholders' equity)
    Total liabilities and owners' equity (or shareholders' equity)

CONSOLIDATED INCOME STATEMENT:
  I. Total operating income:
    operating income
    interest income
    Premium earned
    Fee and commission income
  2. Total operating cost:
    Operating costs
    interest expense
    Fees and Commissions Expenses
    Surrender
    Net payout
    Net withdrawal of insurance liability reserves
    dividend payment policy
    Reinsurance costs
    Taxes and surcharges
    sales expense
    Management costs
    R&D expenses
    Financial expenses
    interest expense
    interest income
    other income
    Investment income (losses are listed with "-")
    Investment income from associates and joint ventures
    Derecognized gains from financial assets measured at amortized cost
    Exchange gains (losses are listed with "-")
    Net exposure hedging gains (losses are listed with "-")
    Gains from changes in fair value (losses are listed with "-")
    Credit impairment losses (losses are listed with "-")
    Asset impairment losses (losses are listed with "-")
    Asset disposal income (losses are listed with "-")
  3. Operating profit (losses are listed with "-"):
    Non-operating income
    Non-operating expenses
  4. Total profits (total losses are listed with "-"):
    income tax expense
  V. Net profit (net losses are listed with "-"):
    (1) Classification by business continuity
    1. Net profit from continuing operations (net losses are listed with "-")
    2. Net profit from discontinued operations (net losses are listed with "-")
    (2) Classification by ownership
    1. Net profit attributable to shareholders of the parent company (net losses are listed with "-")
    2. Profits and losses of minority shareholders (net losses are listed with "-")
  6. Other comprehensive income, net of tax:
    (1) Net after-tax other comprehensive income attributable to owners of the parent company
    1. Other comprehensive income that cannot be reclassified into profit or loss
    (1) Remeasurement of changes in defined benefit plans
    (2) Other comprehensive income that cannot be transferred to profit or loss under the equity method
    (3) Changes in fair value of other equity instrument investments
    (4) Changes in the fair value of the company's own credit risk
    2. Other comprehensive income to be reclassified to profit or loss
    (1) Other comprehensive income that can be transferred to profit or loss under the equity method
    (2) Changes in fair value of other debt investments
    (3) Amount of financial assets reclassified into other comprehensive income
    (4) Provision for credit impairment of other debt investments
    (5) Cash flow hedging reserve
    (6) Differences in translation of foreign currency financial statements
    (7) Others
    (2) After-tax net amount of other comprehensive income attributable to minority shareholders
  7. Total comprehensive income:
    (1) Total comprehensive income attributable to owners of the parent company
    (2) Total comprehensive income attributable to minority shareholders
  8. Earnings per share:
    (1) Basic earnings per share (yuan/share)
    (2) Diluted earnings per share (RMB/share)
  
Consolidated Cash Flow Statement:
  1. Cash flow from operating activities:
    Cash received from sales of goods and rendering of services
    Net increase in customer deposits and interbank deposits
    Net increase in borrowing from the central bank
    Net increase in funds borrowed from other financial institutions
    Cash received from the original insurance contract premium
    Net cash received from reinsurance operations
    Net increase in policyholders' savings and investment funds
    Cash for interest, fees and commissions
    Net increase in borrowed funds
    Net increase in repurchase business funds
    Net cash received from agents buying and selling securities
    Tax Refund
    Other cash received related to operating activities
    Subtotal of cash inflows from operating activities
    Cash for purchasing goods and accepting labor services
    Net increase in loans and advances to customers
    Net increase in deposits with central banks and interbanks
    Cash to pay the original insurance contract compensation
    Net increase in borrowed funds
    Cash for interest, fees and commissions
    Cash to pay policy dividends
    Cash paid to and for employees
    taxes paid
    Payment of other cash related to operating activities
    Subtotal of cash outflows from operating activities
    Net cash flow from operating activities
  2. Cash flow from investing activities:
    Cash back on investment
    Cash received from investment income
    Net cash received from disposal of fixed assets, intangible assets and other long-term assets
    Net cash received from disposal of subsidiaries and other business units
    Other cash received relating to investing activities
    Subtotal of cash inflows from investing activities
    Cash paid for the purchase and construction of fixed assets, intangible assets and other long-term assets
    Cash Investment
    Net increase in mortgage loans
    Net cash paid to acquire subsidiaries and other business units
    Other cash paid relating to investing activities
    Subtotal of cash outflows from investing activities
    Net cash flows from investing activities
  3. Cash flow from financing activities:
    Absorbed cash received from investments
    Subsidiaries absorb cash received from minority shareholders’ investments
    Get cash received from borrowing
    cash received from bond issuance
    Receive other cash related to fundraising activities
    Subtotal of cash inflows from financing activities
    cash paid for debt repayment
    Cash paid to distribute dividends, profits, or repay interest
    dividends and profits paid by subsidiaries to minority shareholders
    Payment of other cash related to fundraising activities
    Subtotal of cash outflows from financing activities
    Net cash flow from financing activities
  4. The impact of exchange rate changes on cash and cash equivalents:
  V. Net increase in cash and cash equivalents:
    Beginning balance of cash and cash equivalents
  6. Balance of cash and cash equivalents at the end of the period: