合并资产负债表:
  流动资产：:
    货币资金
    结算备付金
    拆出资金
    交易性金融资产
    衍生金融资产
    应收票据
    应收账款
    应收款项融资
    预付款项
    应收保费
    应收分保账款
    应收分保合同准备金
    其他应收款
    其中：应收利息
    应收股利
    买入返售金融资产
    存货
    合同资产
    持有待售资产
    一年内到期的非流动资产
    其他流动资产
    流动资产合计
  非流动资产：:
    发放贷款和垫款
    债权投资
    其他债权投资
    长期应收款
    长期股权投资
    其他权益工具投资
    其他非流动金融资产
    投资性房地产
    固定资产
    在建工程
    生产性生物资产
    油气资产
    使用权资产
    无形资产
    开发支出
    商誉
    长期待摊费用
    递延所得税资产
    其他非流动资产
    非流动资产合计
    资产总计
  流动负债：:
    短期借款
    向中央银行借款
    拆入资金
    交易性金融负债
    衍生金融负债
    应付票据
    应付账款
    预收款项
    合同负债
    卖出回购金融资产款
    吸收存款及同业存放
    代理买卖证券款
    代理承销证券款
    应付职工薪酬
    应交税费
    其他应付款
    其中：应付利息
    应付股利
    应付手续费及佣金
    应付分保账款
    持有待售负债
    一年内到期的非流动负债
    其他流动负债
    流动负债合计
  非流动负债：:
    保险合同准备金
    长期借款
    应付债券
    其中：优先股
    永续债
    租赁负债
    长期应付款
    长期应付职工薪酬
    预计负债
    递延收益
    递延所得税负债
    其他非流动负债
    非流动负债合计
    负债合计
  所有者权益（或股东权益）：:
    实收资本（或股本）
    其他权益工具
    其中：优先股
    永续债
    资本公积
    减：库存股
    其他综合收益
    专项储备
    盈余公积
    一般风险准备
    未分配利润
    归属于母公司所有者权益（或股东权益）合计
    少数股东权益
    所有者权益（或股东权益）合计
    负债和所有者权益（或股东权益）总计

合并利润表:
  一、营业总收入:
    其中：营业收入
    利息收入
    已赚保费
    手续费及佣金收入
  二、营业总成本:
    其中：营业成本
    利息支出
    手续费及佣金支出
    退保金
    赔付支出净额
    提取保险责任准备金净额
    保单红利支出
    分保费用
    税金及附加
    销售费用
    管理费用
    研发费用
    财务费用
    其中：利息费用
    利息收入
    加：其他收益
    投资收益（损失以"－"号填列）
    其中：对联营企业和合营企业的投资收益
    以摊余成本计量的金融资产终止确认收益
    汇兑收益（损失以"－"号填列）
    净敞口套期收益（损失以"-"号填列）
    公允价值变动收益（损失以"－"号填列）
    信用减值损失（损失以"－"号填列）
    资产减值损失（损失以"－"号填列）
    资产处置收益（损失以"－"号填列）
  三、营业利润（亏损以"－"号填列）:
    加：营业外收入
    减：营业外支出
  四、利润总额（亏损总额以"－"号填列）:
    减：所得税费用
  五、净利润（净亏损以"－"号填列）:
    （一）按经营持续性分类
    1.持续经营净利润（净亏损以"－"号填列）
    2.终止经营净利润（净亏损以"－"号填列）
    （二）按所有权归属分类
    1.归属于母公司股东的净利润（净亏损以"-"号填列）
    2.少数股东损益（净亏损以"-"号填列）
  六、其他综合收益的税后净额:
    （一）归属母公司所有者的其他综合收益的税后净额
    1.不能重分类进损益的其他综合收益
    （1）重新计量设定受益计划变动额
    （2）权益法下不能转损益的其他综合收益
    （3）其他权益工具投资公允价值变动
    （4）企业自身信用风险公允价值变动
    2.将重分类进损益的其他综合收益
    （1）权益法下可转损益的其他综合收益
    （2）其他债权投资公允价值变动
    （3）金融资产重分类计入其他综合收益的金额
    （4）其他债权投资信用减值准备
    （5）现金流量套期储备
    （6）外币财务报表折算差额
    （7）其他
    （二）归属于少数股东的其他综合收益的税后净额
  七、综合收益总额:
    （一）归属于母公司所有者的综合收益总额
    （二）归属于少数股东的综合收益总额
  八、每股收益：:
    （一）基本每股收益(元/股)
    （二）稀释每股收益(元/股)

合并现金流量表:
  一、经营活动产生的现金流量：:
    销售商品、提供劳务收到的现金
    客户存款和同业存放款项净增加额
    向中央银行借款净增加额
    向其他金融机构拆入资金净增加额
    收到原保险合同保费取得的现金
    收到再保业务现金净额
    保户储金及投资款净增加额
    收取利息、手续费及佣金的现金
    拆入资金净增加额
    回购业务资金净增加额
    代理买卖证券收到的现金净额
    收到的税费返还
    收到其他与经营活动有关的现金
    经营活动现金流入小计
    购买商品、接受劳务支付的现金
    客户贷款及垫款净增加额
    存放中央银行和同业款项净增加额
    支付原保险合同赔付款项的现金
    拆出资金净增加额
    支付利息、手续费及佣金的现金
    支付保单红利的现金
    支付给职工及为职工支付的现金
    支付的各项税费
    支付其他与经营活动有关的现金
    经营活动现金流出小计
    经营活动产生的现金流量净额
  二、投资活动产生的现金流量：:
    收回投资收到的现金
    取得投资收益收到的现金
    处置固定资产、无形资产和其他长期资产收回的现金净额
    处置子公司及其他营业单位收到的现金净额
    收到其他与投资活动有关的现金
    投资活动现金流入小计
    购建固定资产、无形资产和其他长期资产支付的现金
    投资支付的现金
    质押贷款净增加额
    取得子公司及其他营业单位支付的现金净额
    支付其他与投资活动有关的现金
    投资活动现金流出小计
    投资活动产生的现金流量净额
  三、筹资活动产生的现金流量：:
    吸收投资收到的现金
    其中：子公司吸收少数股东投资收到的现金
    取得借款收到的现金
    发行债券所收到的现金
    收到其他与筹资活动有关的现金
    筹资活动现金流入小计
    偿还债务支付的现金
    分配股利、利润或偿付利息支付的现金
    其中：子公司支付给少数股东的股利、利润
    支付其他与筹资活动有关的现金
    筹资活动现金流出小计
    筹资活动产生的现金流量净额
  四、汇率变动对现金及现金等价物的影响 :
  五、现金及现金等价物净增加额:
    加：期初现金及现金等价物余额
  六、期末现金及现金等价物余额:

合并及银行资产负债表:
  资产:
    现金及存放中央银行款项
    存放同业款项
    拆出资金
    衍生金融资产
    买入返售金融资产
    发放贷款和垫款
    金融投资
    交易性金融资产
    债权投资
    其他债权投资
    其他权益工具投资
    长期股权投资
    固定资产
    无形资产
    递延所得税资产
    其他资产
    资产总计
  负债:
    向中央银行借款
    同业及其他金融机构存放款项
    拆入资金
    衍生金融负债
    卖出回购金融资产款
    吸收存款
    应付职工薪酬
    应交税费
    应付债务凭证
    预计负债
    其他负债
    负债合计
  股东权益:
    股本
    其他权益工具
    其中：优先股
    永续债
    资本公积
    其他综合收益
    盈余公积
    一般风险准备
    未分配利润
    归属于母公司股东权益合计
    少数股东权益
    股东权益合计
    负债及股东权益总计

合并及银行利润表:
  一、营业收入:
    利息净收入
    利息收入
    利息支出
    手续费及佣金净收入
    手续费及佣金收入
    手续费及佣金支出
    投资收益
    其中：以摊余成本计量的金
    融资产终止确认产生的收益
    公允价值变动收益
    汇兑收益/(损失)
    其他业务收入
    资产处置损益
    其他收益
  二、营业支出:
    税金及附加
    业务及管理费
    信用减值损失
    其他资产减值损失
    其他业务成本
  三、营业利润:
    加：营业外收入
    减：营业外支出
  四、利润总额:
    减：所得税费用
  五、净利润:
    (一)按经营持续性分类
    1、持续经营净利润
    2、终止经营净利润
    (二)按所有权归属分类
    1、归属于母公司股东的净利润
    2、少数股东损益
  六、其他综合收益税后净额:
    (一)以后不能重分类进损益的其他综合收益
    1、其他权益工具投资公允价值变动
    (二)以后将重分类进损益的其他综合收益
    1、以公允价值计量且其变动计入其他
    综合收益的金融资产公允价值变动
    2、以公允价值计量且其变动计入其他
    综合收益的金融资产投资信用损失准备
    归属于母公司股东的其他综合收益税后净额
    归属于少数股东的其他综合收益税后净额
  七、综合收益总额:
    归属于母公司股东的综合收益总额
    归属于少数股东的综合收益总额
  八、每股收益:
    基本每股收益(人民币元)

合并及银行现金流量表:
  经营活动产生的现金流量:
    客户存款和同业及其他金融机构
    存放款项净增加额
    存放中央银行和同业款项净减少额
    拆入资金及卖出回购金融资产款净增加额
    拆出资金及买入返售金融资产净减少额
    为交易目的而持有的金融资产净减少额
    经营性应付债务凭证净增加额
    收取利息、手续费及佣金的现金
    收到其他与经营活动有关的现金
    经营活动现金流入小计
    客户贷款和垫款净增加额
    存放中央银行和同业款项净增加额
    拆入资金及卖出回购金融资产款净减少额
    拆出资金及买入返售金融资产净增加额
    向中央银行借款净减少额
    为交易目的而持有的金融资产净增加额
    支付利息、手续费及佣金的现金
    支付给职工以及为职工支付的现金
    支付的各项税费
    支付其他与经营活动有关的现金
    经营活动现金流出小计
    经营活动产生的现金流量净额
  投资活动产生的现金流量:
    收回投资收到的现金
    取得投资收益收到的现金
    处置固定资产、无形资产和
    其他长期资产收到的现金净额
    投资活动现金流入小计
    投资支付的现金
    购建固定资产、无形资产和
    其他长期资产支付的现金
    投资活动现金流出小计
    投资活动产生的现金流量净额
  筹资活动产生的现金流量:
    吸收投资收到的现金
    发行债券所收到的现金
    筹资活动现金流入小计
    偿还债务支付的现金
    分配股利、利润或偿付利息支付的现金
    筹资活动现金流出小计
    筹资活动产生的现金流量净额
    汇率变动对现金及现金等价物的影响额
    现金及现金等价物净变动额
    加：期初现金及现金等价物余额
    期末现金及现金等价物余额

合并银行股东权益变动表:
  一、2018 年 12 月 31 日余额(经审计):
    会计政策变更
    2019年1月1日余额
  二、本期增减变动金额:
    (一)净利润
    (二)其他综合收益
    上述(一)和(二)小计
    (三)股东投入资本
    1.其他权益工具持有者投入资本
    (四)利润分配
    1.提取盈余公积
    2.提取一般风险准备
    3.普通股股利分配
    4.对其他权益工具持有者的利润分配
  三、2019 年 6 月 30 日余额(未经审计):
  四、2019 年 7 月 1 日余额(未经审计):
  五、本期增减变动金额:
    (一)净利润
    (二)其他综合收益
    上述(一)和(二)小计
    (三)利润分配
    1.提取盈余公积
    2.提取一般风险准备
    3.普通股股利分配
    4.对其他权益工具持有者的利润分配
  六、2019 年 12 月 31 日余额(经审计):

合并及公司资产负债表:
  资产:
    货币资金
    以公允价值计量且其变动计入
    当期损益的金融资产
    买入返售金融资产
    应收利息
    应收保费
    应收分保账款
    应收分保未到期责任准备金
    应收分保未决赔款准备金
    应收分保寿险责任准备金
    应收分保长期健康险责任准备金
    保户质押贷款
    其他应收款
    定期存款
    可供出售金融资产
    持有至到期投资
    归入贷款及应收款的投资
    长期股权投资
    存出资本保证金
    投资性房地产
    固定资产
    在建工程
    使用权资产
    无形资产
    递延所得税资产
    其他资产
    独立账户资产
    资产总计
  负债:
    以公允价值计量且其变动计入
    当期损益的金融负债
    卖出回购金融资产款
    预收保费
    应付手续费及佣金
    应付分保账款
    应付职工薪酬
    应交税费
    应付股利
    应付赔付款
    应付保单红利
    其他应付款
    保户储金及投资款
    未到期责任准备金
    未决赔款准备金
    寿险责任准备金
    长期健康险责任准备金
    应付债券
    租赁负债
    预计负债
    递延收益
    递延所得税负债
    其他负债
    独立账户负债
    负债合计
  负债及股东权益:
    股东权益
    股本
    资本公积
    其他综合收益
    盈余公积
    一般风险准备
    未分配利润
    归属于母公司股东的股东权益合计
    少数股东权益
    股东权益合计
    负债及股东权益总计

合并及公司利润表:
  一、营业收入:
    已赚保费
    保险业务收入
    减 ：分出保费
     提取未到期责任准备金
    投资收益
    其中 ：对联营企业和合营企业
    的投资收益
    公允价值变动损益
    汇兑损益
    其他收益
    其他业务收入
  二、营业支出:
    退保金
    赔付支出
    减 ：摊回赔付支出
    提取保险责任准备金
    减 ：摊回保险责任准备金
    保单红利支出
    税金及附加
    手续费及佣金支出
    业务及管理费
    减 ：摊回分保费用
    其他业务成本
    资产减值损失
  三、营业利润:
    加 ：营业外收入
    减 ：营业外支出
    四、利润总额
    减 ：所得税费用
  五、净利润:
    （一）按经营持续性分类 ：
    持续经营净利润
    （二）按所有权归属分类 ：
    归属于母公司股东的净利润
    少数股东损益
  六、其他综合收益的税后净额:
    归属于母公司股东的其他综合收益的税后净额
    将重分类进损益的其他
    综合收益
    权益法下可转损益的其他综合收益及其对保险合同准备金和保户储金及投资款 的影响的税后净额
    可供出售金融资产公允价值变动及其对保险合同准备金和保户储金及投资款的影响的税后净额
    外币财务报表折算差额
    归属于少数股东的其他综合
    收益的税后净额
  七、综合收益总额:
    归属于母公司股东的综合收益总额
    归属于少数股东的综合收益总额
  八、每股收益:
    基本每股收益
    稀释每股收益

合并及公司现金流量表:
  一、经营活动产生的现金流量:
    收到原保险合同保费取得的现金
    保户储金及投资款净增加额
    收到其他与经营活动有关的现金
    经营活动现金流入小计
    支付原保险合同赔付款项的现金
    支付再保险业务现金净额
    支付手续费及佣金的现金
    支付保单红利的现金
    支付给职工以及为职工支付的现金
    支付的各项税费
    支付其他与经营活动有关的现金
    经营活动现金流出小计
    经营活动产生的现金流量净额
  二、投资活动产生的现金流量:
    收回投资收到的现金
    取得投资收益收到的现金
    处置固定资产、无形资产和其他
    长期资产收回的现金净额
    收到买入返售金融资产的现金净额
    收购结构化主体收到的现金
    投资活动现金流入小计
    投资支付的现金
    保户质押贷款净增加额
    购建固定资产、无形资产和其他长
    期资产所支付的现金
    处置结构化主体产生的现金流量净额
    支付其他与投资活动有关的现金
    投资活动现金流出小计
    投资活动产生的现金流量净额
  三、筹资活动产生的现金流量:
    吸收投资收到的现金
    其中 ：结构化主体吸收少数股东投资
    收到的现金
    收到卖出回购金融资产款的现金净额
    发行债券收到的现金
    筹资活动现金流入小计
    支付卖出回购金融资产款的现金净额
    分配股利、利润或偿付利息支付的现金
    其中 ：结构化主体支付给少数股东的
    股利
    偿还租赁负债本金和支付利息所支付的
    现金
    支付其他与筹资活动有关的现金
    筹资活动现金流出小计
    筹资活动产生的现金流量净额
  四、汇率变动对现金及现金等价物的影响额:
  五、现金及现金等价物净增加额:
    加 ：期初现金及现金等价物余额
  六、期末现金及现金等价物余额:

公司股东权益变动(多表)表:
  2019年1月1日:
    本期增减变动额
    综合收益总额
    利润分配
    提取盈余公积
    对股东的分配
    其他
    对联营企业和合营企业权益法
    核算引起的其他权益变动
  2019年6月30日:

(证券)合并资产负债表:
  资产：:
    货币资金
    其中：客户资金存款
    结算备付金
    其中：客户备付金
    融出资金
    衍生金融资产
    存出保证金
    应收款项
    买入返售金融资产
    金融投资：
    交易性金融资产
    其他债权投资
    其他权益工具投资
    投资性房地产
    固定资产
    在建工程
    无形资产
    商誉
    递延所得税资产
    其他资产
    资产总计
  负债：:
    应付短期融资款
    拆入资金
    交易性金融负债
    衍生金融负债
    卖出回购金融资产款
    代理买卖证券款
    代理承销证券款
    应付职工薪酬
    应交税费
    应付款项
    应付债券
    递延所得税负债
    其他负债
    负债合计
  所有者权益（或股东权益）：:
    实收资本（或股本）
    资本公积
    其他综合收益
    盈余公积
    一般风险准备
    未分配利润
    归属于母公司所有者权益（或股东权益）合计
    少数股东权益
    所有者权益（或股东权益）合计
    负债和所有者权益（或股东权益）总计

母公司利润表:
  一、营业总收入:
    利息净收入
    其中：利息收入
    利息支出
    手续费及佣金净收入
    其中：经纪业务手续费净收入
    投资银行业务手续费净收入
    资产管理业务手续费净收入
    投资收益（损失以"-"号填列）
    其中：对联营企业和合营企业的投资收益
    其他收益
    公允价值变动收益（损失以"-"号填列）
    汇兑收益（损失以"-"号填列）
    其他业务收入
    资产处置收益（损失以"－"号填列）
  二、营业总支出:
    税金及附加
    业务及管理费
    信用减值损失
    其他资产减值损失
    其他业务成本
  三、营业利润（亏损以"-"号填列）:
    加：营业外收入
    减：营业外支出
    四、利润总额（亏损总额以"-"号填列）
    减：所得税费用
  五、净利润（净亏损以"－"号填列）:
    （一）按经营持续性分类
    1.持续经营净利润（净亏损以"－"号填列）
    2.终止经营净利润（净亏损以"－"号填列）
    （二）按所有权归属分类
    1.归属于母公司股东的净利润（净亏损以"-"号填列）
    2.少数股东损益（净亏损以"-"号填列）
  六、其他综合收益的税后净额:
    归属母公司所有者的其他综合收益的税后净额
    （一）不能重分类进损益的其他综合收益
    1.重新计量设定受益计划变动额
    2.其他权益工具投资公允价值变动
    （二）将重分类进损益的其他综合收益
    1.权益法下可转损益的其他综合收益
    2.其他债权投资公允价值变动
    3.其他债权投资信用损失准备
    4.外币财务报表折算差额
    归属于少数股东的其他综合收益的税后净额
  七、综合收益总额:
    归属于母公司所有者的综合收益总额
    归属于少数股东的综合收益总额
    八、每股收益：
    （一）基本每股收益(元/股)
    （二）稀释每股收益(元/股)

母公司现金流量表:
  一、经营活动产生的现金流量：:
    收取利息、手续费及佣金的现金
    拆入资金净增加额
    回购业务资金净增加额
    代理买卖证券收到的现金净额
    收到其他与经营活动有关的现金
    经营活动现金流入小计
    为交易目的而持有的金融资产净增加额
    融出资金净增加额
    支付利息、手续费及佣金的现金
    支付给职工及为职工支付的现金
    支付的各项税费
    支付其他与经营活动有关的现金
    经营活动现金流出小计
    经营活动产生的现金流量净额
  二、投资活动产生的现金流量：:
    收回投资收到的现金
    取得投资收益收到的现金
    处置固定资产、无形资产和其他长期资产收回的现金净额
    投资活动现金流入小计
    投资支付的现金
    购建固定资产、无形资产和其他长期资产支付的现金
    投资活动现金流出小计
    投资活动产生的现金流量净额
  三、筹资活动产生的现金流量：:
    发行债券收到的现金
    筹资活动现金流入小计
    偿还债务支付的现金
    分配股利、利润或偿付利息支付的现金
    筹资活动现金流出小计
    筹资活动产生的现金流量净额
  四、汇率变动对现金及现金等价物的影响:
  五、现金及现金等价物净增加额:
    加：期初现金及现金等价物余额
  六、期末现金及现金等价物余额:

合并所有者权益变动表(复表):
  一、上年期末余额:
    加：会计政策变更
    前期差错更正
    其他
  二、本年期初余额:
  三、本期增减变动金额（减少以"－"号填列）:
    （一）综合收益总额0
    （二）所有者投入和减少资本
    1．所有者投入的普通股
    2．其他权益工具持有者投入资本
    3．股份支付计入所有者权益的金额
    4．其他
    （三）利润分配
    1．提取盈余公积
    2．提取一般风险准备
    3．对所有者（或股东）的分配
    4．其他
    （四）所有者权益内部结转
    1．资本公积转增资本（或股本）
    2．盈余公积转增资本（或股本）
    3．盈余公积弥补亏损
    4．设定受益计划变动额结转留存收益
    5．其他综合收益结转留存收益
    6．其他
    （五）其他
  四、本期期末余额:

母公司所有者权益变动表(复表):
  一、上年期末余额:
    加：会计政策变更
    前期差错更正
    其他
  二、本年期初余额:
  三、本期增减变动金额（减少以"－"号填列）:
    （一）综合收益总额
    （二）所有者投入和减少资本
    1．所有者投入的普通股
    2．其他权益工具持有者投入资本
    3．股份支付计入所有者权益的金额
    4．其他
    （三）利润分配
    1．提取盈余公积
    2．提取一般风险准备
    3．对所有者（或股东）的分配
    4．其他
    （四）所有者权益内部结转
    1．资本公积转增资本（或股本）
    2．盈余公积转增资本（或股本）
    3．盈余公积弥补亏损
    4．设定受益计划变动额结转留存收益
    5．其他综合收益结转留存收益
    6．其他
  四、本期期末余额: