random:
  vrules: 0.5     #横线
  hrules: 1       #纵线
  page_it: 0.5    #分页
  max_lines: 40   #分页最大行
  cols: 3
  hstack: 0.5    #不分页而是堆叠
  vstack: 0.2    # 多表
  indent: 2      #缩进量
  bold: 0.3      #数字加粗
  fix_table_width: 0.5 # 固定表格宽度概率、造成换行
  max_table_width: 200
  min_table_width: 100

  merge: 0.5  # 合并空表格的概率或者不处理的概率
  color_it: 0.2 # 增加背景颜色的概率
  highlight: 0.2 # 高亮的概率